# Inferential Statistics
## Sampling Techniques
Imagine you are building a fraud detection ML model.

Population = all transactions in the world

Reality:

95% → Normal transactions

5% → Fraud transactions

Your job:

Pick a training dataset that teaches the model the truth about the world.

In [2]:
import numpy as np
import pandas as pd

np.random.seed(42)

# Created Population
data = pd.DataFrame({
    "transaction_amount" : np.random.normal(100,20,1000),
    "is_fraud" : np.concatenate([
        np.zeros(950), # 95% normal
        np.ones(50) # 5% fraud
    ])
})

data["is_fraud"].value_counts(normalize=True)

is_fraud
0.0    0.95
1.0    0.05
Name: proportion, dtype: float64

#### Stratified Sampling

In [4]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(
    data,
    test_size=0.9, # test data size 90% test and 10% training
    stratify=data["is_fraud"], # ensures the proportion of fraud and not fraud in both datasets test and train
    random_state=42
)

train["is_fraud"].value_counts(normalize=True) # normalizing beacuse we want the proportion and not the count of the data 
# without normalizing we get the counts like 950 and 50

is_fraud
0.0    0.95
1.0    0.05
Name: proportion, dtype: float64

#### Random Sampling

In [11]:
random_sample = data.sample(n=100) # taking 100 sample values from the data
random_sample["is_fraud"].value_counts(normalize=True) # notice the proportion is not the same as the original datasets

is_fraud
0.0    0.94
1.0    0.06
Name: proportion, dtype: float64

#### Systematic Sampling

In [13]:
systematic_sample = data.iloc[::10] # taking every tenth data point from the dataseet 
systematic_sample["is_fraud"].value_counts(normalize=True)

is_fraud
0.0    0.95
1.0    0.05
Name: proportion, dtype: float64

#### Cluster Sampling

In [13]:
# Create Clusters (hospitals)
hospital_data = pd.DataFrame( {
    "hospital_id" : np.repeat([1,2,3,4,5], 200), # creating 5 clusters each of size 200 
    "age" : np.random.randint(20, 80, 1000), # random ages between 20 and 80 for 1000 patients
    "disease" : np.random.choice([0,1], size=1000, p=[0.95,0.05]) # randomly assign disease status(0 or 1) to each patient
    # 0 will be chosen 95% of time and 1 for the rest 5% times
})

# Select only hospitals 1 and 2 
cluster_sample = hospital_data[hospital_data["hospital_id"].isin([1,2])]  # select all rows in hospitals 1 and 2

cluster_sample["disease"].value_counts(normalize=True) # - This shows the proportion of patients with and without disease in the selected clusters.

disease
0    0.95
1    0.05
Name: proportion, dtype: float64

In [19]:
hospital_data

     hospital_id  age  disease
0              1   79        0
1              1   42        0
2              1   36        0
3              1   20        0
4              1   74        0
..           ...  ...      ...
995            5   60        1
996            5   35        0
997            5   53        0
998            5   51        0
999            5   45        0

[1000 rows x 3 columns]

#### Convinience Sampling

In [22]:
# add a time feature
hospital_data["recent_user"] = np.random.choice([0,1], size=1000, p=[0.7,0.3]) # adds a new coloumn to the dataset assigned 1 for recently visited patients and 0 for rest

# Convinience sample : only recent users
convinience_sample = hospital_data[hospital_data["recent_user"] == 1] # takings rows which satisfies the condition that is : to be a recently visited patient

convinience_sample["disease"].value_counts(normalize=True) # shows the proportion of recently visited patients who have the disease and who doesn't have the disease

disease
0    0.954128
1    0.045872
Name: proportion, dtype: float64

In [3]:
import pandas as pd
from scipy.stats import chi2_contingency

data = pd.DataFrame({
    "Gender": ["Male", "Male", "Female", "Female", "Male", "Female"],
    "Churn":  ["Yes", "No", "Yes", "No", "No", "No"]
})

contingency = pd.crosstab(data["Gender"], data["Churn"])
contingency

Churn   No  Yes
Gender
Female   2    1
Male     2    1

In [5]:
chi_stat, p_value, dof, expected = chi2_contingency(contingency)

chi_stat, p_value, expected

(np.float64(0.0),
 np.float64(1.0),
 array([[2., 1.],
        [2., 1.]]))

In [2]:
import numpy as np
from scipy.stats import chisquare

observed = np.array([8, 9, 10, 11, 12, 10])
expected = np.array([10, 10, 10, 10, 10, 10])

chi_stat, p_value = chisquare(f_obs=observed, f_exp=expected)

chi_stat, p_value

(np.float64(1.0), np.float64(0.9625657732472964))

Hypothesis Tests.

import numpy as np
from statsmodels.stats.weightstats import ztest

data = np.array([1,2,3,4,5,6,7,8,9,10])

z_stat , p_value = ztest(data, value = 50)

print("Z :",z_stat_stat)
print("P :", p_value)

In [5]:
import numpy as np
from scipy import stats

data = np.array([10,11,13,12,15])

t, p = stats.ttest_1samp(data, 13)

print(p)

0.40502331430906013

In [6]:
a = [20,22,24,26,28]
b = [18,19,21,23,25]

t,p = stats.ttest_ind(a,b)

p

np.float64(0.18039544877850114)

In [10]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

t,p = stats.ttest_rel(b, a)

p

e:\vs_env\lib\site-packages\scipy\stats\_axis_nan_policy.py:430: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return hypotest_fun_in(*args, **kwds)

np.float64(0.0)